
\NeedsTeXFormat{LaTeX2e}
\ProvidesClass{thesis}

\LoadClass[twoside, titlepage, DIV=8, BCOR=8.5mm, open=right]{scrreprt}

\RequirePackage{fixltx2e}
\RequirePackage{xltxtra}
\RequirePackage{etoolbox}
\RequirePackage{fontspec}
\RequirePackage{pifont}
\RequirePackage{amsmath}
\RequirePackage{unicode-math}
\RequirePackage{setspace}
\RequirePackage[markcase=lower]{scrlayer-scrpage}
\RequirePackage{xcolor}
\RequirePackage{marginnote}
\RequirePackage{float}
\RequirePackage[inline]{enumitem}
\RequirePackage{wrapfig}
\RequirePackage{microtype}
\RequirePackage{tocstyle}
\RequirePackage{polyglossia}
\RequirePackage[natbib, backend=biber, style=authoryear, maxcitenames=2, maxbibnames=99, useprefix]{biblatex}
\RequirePackage{booktabs}
\RequirePackage{tabu}
\RequirePackage{longtable}
\RequirePackage{collcell}
\RequirePackage[all]{onlyamsmath}
\RequirePackage{siunitx}
\RequirePackage{nth}
\RequirePackage{textcase}
\RequirePackage[english, iso]{isodate}
\RequirePackage{xspace}
\RequirePackage[version=3]{mhchem}
\RequirePackage{minted}
\RequirePackage[explicit]{titlesec}
\RequirePackage{scalefnt}
\RequirePackage{caption}
\RequirePackage{subcaption}
\RequirePackage{ragged2e}
\RequirePackage{ifoddpage}
\RequirePackage{adjustbox}
\RequirePackage{hyperref} % [glossaries] “You must load hyperref *first*”
\RequirePackage[xindy, toc, nopostdot]{glossaries}
% “… cleveref must be loaded *last*”
\RequirePackage[nameinlink, noabbrev]{cleveref}

