#!/usr/bin/env bash

declare -a arr=(".out" ".aux"
                ".bcf" ".toc"
                ".lot" ".log"
                ".lof" ".lof"
                ".fls" "fdb_latexmk"
                "run.xml" ".blg"
                ".bbl" ".glo"
                ".gls" ".xdy"
                ".glg" ".run.xml")

for f in "$@"; do
    for i in "${arr[@]}"; do
        [ -f $f$i ] && rm $f$i && echo "$f$i deleted"|| echo ""
    done
done

